---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: destination-instance-kyma
spec:
  clusterServiceClassExternalName: destination
  clusterServicePlanExternalName: lite
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: destination-binding-kyma
spec:
  instanceRef:
    name: destination-instance-kyma

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: xsuaa-instance-kyma
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    xsappname: xsapp-kyma
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        # callback
        - "https://fioriapp.<cluster-domain>/**"

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: xsuaa-binding-kyma
spec:
  instanceRef:
    name: xsuaa-instance-kyma